# Generated by Django 5.2.7 on 2025-10-28 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_date', models.DateField()),
                ('end_date', models.DateField()),
                ('from_to', models.CharField(blank=True, max_length=255, null=True)),
                ('due_to', models.ManyToManyField(blank=True, related_name='assigned_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
            },
        ),
    ]
