# Generated by Django 5.2.7 on 2025-11-04 15:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mission', 'verbose_name_plural': 'Missions'},
        ),
        migrations.RemoveField(
            model_name='mission',
            name='task_id',
        ),
        migrations.AddField(
            model_name='mission',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
