# Generated by Django 5.2.7 on 2025-12-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="deadline_alerts",
            field=models.BooleanField(default=True, verbose_name="Termin Uyarıları"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Departman"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_notifications",
            field=models.BooleanField(
                default=True, verbose_name="E-posta Bildirimleri"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="notification_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Bildirim E-posta"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefon"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_photos/",
                verbose_name="Profil Fotoğrafı",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="task_reminders",
            field=models.BooleanField(
                default=True, verbose_name="Görev Hatırlatıcıları"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("CEO", "CEO"),
                    ("MANAGER", "Manager"),
                    ("EMPLOYEE", "Employee"),
                ],
                default="EMPLOYEE",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="unvan",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ünvan"
            ),
        ),
    ]
