# Generated by Django 5.2.7 on 2025-12-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_projectcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="department",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="İlgilenen Departman",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Düşük"), ("MEDIUM", "Orta"), ("HIGH", "Yüksek")],
                default="MEDIUM",
                max_length=10,
                verbose_name="Öncelik",
            ),
        ),
    ]
