# Generated by Django 5.2.7 on 2025-12-12 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_mission_department_mission_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MISSION_ASSIGN", "Görev Ataması"),
                            ("PROJECT_INVITE", "Proje Daveti"),
                            ("PROJECT_COMMENT", "Yeni Yorum"),
                            ("MISSION_COMPLETE", "Görev Tamamlandı"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("related_id", models.IntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
