# Generated by Django 5.2.7 on 2025-12-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Yapılacak"),
                    ("IN_PROGRESS", "Devam Ediyor"),
                    ("COMPLETED", "Tamamlandı"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
    ]
