# Generated by Django 5.2.7 on 2025-12-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_mission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Departman"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Bitiş Tarihi"),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Başlangıç Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="topic",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Konu"
            ),
        ),
    ]
